src/Entity/Questions.php
<?php

namespace App\Entity;

use ApiPlatform\Core\Annotation\ApiResource;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;


/**
 * @ApiResource()
 * @ORM\Table(options={"collate"="utf8_general_ci"})
 * @ORM\Entity(repositoryClass="App\Repository\QuestionsRepository")
 * @Gedmo\Loggable(logEntryClass="App\Entity\LogQuestions")
 */
class Questions
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     * @Gedmo\Versioned()
     */
    private $template_id;

    /**
     * @ORM\Column(type="integer")
     * @Gedmo\Versioned()
     */
    private $question_id;

    /**
     * @ORM\Column(type="integer")
     * @Gedmo\Versioned()
     */
    private $question_option_id;

    /**
     * @ORM\Column(type="integer")
     * @Gedmo\Versioned()
     */
    private $score;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTemplateId(): ?int
    {
        return $this->template_id;
    }

    public function setTemplateId(int $template_id): self
    {
        $this->template_id = $template_id;

        return $this;
    }

    public function getQuestionId(): ?int
    {
        return $this->question_id;
    }

    public function setQuestionId(int $question_id): self
    {
        $this->question_id = $question_id;

        return $this;
    }

    public function getQuestionOptionId(): ?int
    {
        return $this->question_option_id;
    }

    public function setQuestionOptionId(int $question_option_id): self
    {
        $this->question_option_id = $question_option_id;

        return $this;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(int $score): self
    {
        $this->score = $score;

        return $this;
    }
}

src/Form/QuestionsType.php
<?php

namespace App\Form;

use App\Entity\Questions;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class QuestionsType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('template_id')
            ->add('question_id')
            ->add('question_option_id')
            ->add('score')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Questions::class,
        ]);
    }
}

src/Controller/QuestionsController.php
<?php

namespace App\Controller;

use App\Entity\Questions;
use App\Form\QuestionsType;
use App\Repository\QuestionsRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/questions")
 */
class QuestionsController extends AbstractController
{
    /**
     * @Route("/", name="questions_index", methods={"GET"})
     */
    public function index(QuestionsRepository $questionsRepository): Response
    {
        return $this->render('questions/index.html.twig', [
            'questions' => $questionsRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="questions_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $question = new Questions();
        $form = $this->createForm(QuestionsType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($question);
            $entityManager->flush();

            return $this->redirectToRoute('questions_index');
        }

        return $this->render('questions/new.html.twig', [
            'question' => $question,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="questions_show", methods={"GET"})
     */
    public function show(Questions $question): Response
    {
        return $this->render('questions/show.html.twig', [
            'question' => $question,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="questions_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Questions $question): Response
    {
        $form = $this->createForm(QuestionsType::class, $question);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('questions_index');
        }

        return $this->render('questions/edit.html.twig', [
            'question' => $question,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="questions_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Questions $question): Response
    {
        if ($this->isCsrfTokenValid('delete'.$question->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($question);
            $entityManager->flush();
        }

        return $this->redirectToRoute('questions_index');
    }
}

templates/questions/_delete_form.html.twig
<form method="post" action="{{ path('questions_delete', {'id': question.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ question.id) }}">
    <button class="btn">Delete</button>
</form>

templates/questions/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/questions/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Questions{% endblock %}

{% block body %}
    <h1>Edit Questions</h1>

    {{ include('questions/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('questions_index') }}">back to list</a>

    {{ include('questions/_delete_form.html.twig') }}
{% endblock %}

templates/questions/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questions index{% endblock %}

{% block body %}
    <h1>Questions index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Template_id</th>
                <th>Question_id</th>
                <th>Question_option_id</th>
                <th>Score</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for question in questions %}
            <tr>
                <td>{{ question.id }}</td>
                <td>{{ question.templateId }}</td>
                <td>{{ question.questionId }}</td>
                <td>{{ question.questionOptionId }}</td>
                <td>{{ question.score }}</td>
                <td>
                    <a href="{{ path('questions_show', {'id': question.id}) }}">show</a>
                    <a href="{{ path('questions_edit', {'id': question.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('questions_new') }}">Create new</a>
{% endblock %}

templates/questions/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Questions{% endblock %}

{% block body %}
    <h1>Create new Questions</h1>

    {{ include('questions/_form.html.twig') }}

    <a href="{{ path('questions_index') }}">back to list</a>
{% endblock %}

templates/questions/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Questions{% endblock %}

{% block body %}
    <h1>Questions</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ question.id }}</td>
            </tr>
            <tr>
                <th>Template_id</th>
                <td>{{ question.templateId }}</td>
            </tr>
            <tr>
                <th>Question_id</th>
                <td>{{ question.questionId }}</td>
            </tr>
            <tr>
                <th>Question_option_id</th>
                <td>{{ question.questionOptionId }}</td>
            </tr>
            <tr>
                <th>Score</th>
                <td>{{ question.score }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('questions_index') }}">back to list</a>

    <a href="{{ path('questions_edit', {'id': question.id}) }}">edit</a>

    {{ include('questions/_delete_form.html.twig') }}
{% endblock %}